name: h5iotest_kmu
on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug
  LOCAL: local

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v2

      - name: Cache Spack packages
        uses: actions/cache@v2
        id: spack-cache
        with:
          path: ~/${{ env.LOCAL }}
          key: ${{ runner.os }}-${{ hashFiles('ci/**') }}

      - name: Install APT Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y autoconf
          sudo apt-get install -y automake
          sudo apt-get install -y libtool
          sudo apt-get install -y libtool-bin
          sudo apt-get install -y mpich
          sudo apt-get install -y lcov
          sudo apt-get install -y zlib1g-dev
          sudo apt-get install -y libsdl2-dev

      - name: Build And Install Dependencies
        if: steps.spack-cache.outputs.cache-hit != 'true'
        run: ci/install_deps_cmake.sh

      - name: Build and Test
        run: ci/install_h5iotest_kmu.sh
