name: spack ior
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Sources
      uses: actions/checkout@v2
    
    - name: Checkout Spack
      uses: actions/checkout@v2
      with:
        repository: spack/spack
        path: ./spack

    - name: Checkout Mochi
      uses: actions/checkout@v2
      with:
        repository: mochi-hpc/mochi-spack-packages
        ref: f015ae93717ac3b81972c55116c3b91aa9c645e4
        path: ./mochi-spack-packages

    - name: Run Spack
      run: |
        . ./spack/share/spack/setup-env.sh
        spack compiler find
        spack repo add ./mochi-spack-packages
        spack repo add ./ci/hermes
        # spack bootstrap untrust github-actions
        spack -d install catch2@2.13.3
        # spack install ior+hermes
