name: ubuntu latest

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  BUILD_TYPE: Debug
  LOCAL: local

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v4

      - name: Install APT Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y docker

      - name: Build And Install Dependencies
        run: ci/install_deps.sh

      - name: Build
        run: |
      - name: Build and Test
        run: docker exec /hermes_deps_c bash /hermes/ci/install_hermes.sh
