name: ubuntu latest

on:
  push:
    branches: [ master- ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  BUILD_TYPE: Debug
  LOCAL: local

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Sources
        uses: actions/checkout@v3

      - name: Run cpplint
        run: pip install cpplint==1.5.4 && bash ci/lint.sh `pwd`

      - name: Install APT Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y -q autoconf
          sudo apt-get install -y -q automake
          sudo apt-get install -y -q cpanminus
          sudo apt-get install -y -q libtool
          sudo apt-get install -y -q libtool-bin
          sudo apt-get install -y -q mpich
          sudo apt-get install -y -q lcov
          sudo apt-get install -y -q zlib1g-dev
          sudo apt-get install -y -q libsdl2-dev
          sudo apt-get install -y -q diffutils
          sudo apt-get install -y -q libdb-dev
          sudo apt-get install -y -q libedit-dev
          sudo apt-get install -y -q libgdbm-dev          
          sudo apt-get install -y -q libncurses6
          sudo apt-get install -y -q libreadline-dev
          sudo apt-get install -y -q libsigsegv-dev
          sudo apt-get install -y -q libxml2-dev
          sudo apt-get install -y -q openssl
          sudo apt-get install -y -q pkgconf
          sudo apt-get install -y -q xz-utils


      - name: Install
        run: pushd build && make install && popd

